import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ims, ImsWeb.Endpoint,
  url: [
    host: "159.65.234.146",
    scheme: "https",
    port: 443
  ],
  # force_ssl: [
  #   rewrite_on: [:x_forwarded_proto]
  # ],
  check_origin: [
    "http://159.65.234.146"
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Ims.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.



# echo 'export SECRET_KEY_BASE=Csskc6M2we39yODInUM6N5xifDGjp7UJl2bUEnzCdqCG0Rfe6anOm5Dh/bGZTnT2m+FuOvwf6MD07mlW1xZF2g==' >> ~/.bashrc
